/* eslint-disable */
/**
 * Generated `api` utility.
 * This file is compatible with Convex codegen and will be regenerated by Convex CLI.
 */
import { anyApi, componentsGeneric } from "convex/server";

export const api = anyApi;
export const internal = anyApi;
export const components = componentsGeneric();
